//TEST DE CONNECTION ET OBTENTION OU NON D'UN TOKEN

### correct user details

POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email": "mac@gmail.com",
    "password": "Facile-26"
}

### Change Password

POST http://localhost:4000/api/change-password/48
Content-Type: application/json

{   
    "password": "Facile-26"
}

### correct admin details

POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email": "user32@example.com",
    "password": "Password$123"
}


//TEST D'ACCES OU NON A LA ROUTE PROTEGEE /users EN FONCTION DES DONNÉES DU TOKEN (admin ou user)

### with admin token

GET http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ4LCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNzA4MjAxMDMyfQ.MVAQ7viCetBK-3v76f5rguDsjOp2SGVRRFYk4alqF34

### with non admin token

GET http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ3LCJ1c2VyUm9sZSI6InVzZXIiLCJpYXQiOjE3MDgyMDA1Mjd9.0yB9y6ZG-h_Po8HtYDJDunk_LqskBXvai6i7yjCsJN0

### Adding user 

POST http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ4LCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNzA4MjAxMDMyfQ.MVAQ7viCetBK-3v76f5rguDsjOp2SGVRRFYk4alqF34
Content-Type: application/json

{
    "enterprise": "DOD",
    "email": "mac@gmail.com",
    "firstname": "Raoul",
    "lastname": "Macintosh",
    "password": "Password$123",
    "position": "Agent",
    "process": "SSE",
    "role_id":2
}

### Récuperer 1 Utilisateur précis
GET http://localhost:4000/api/users/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI4LCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNzA3ODc2NjA2fQ.pWXKMEoWgeIsAr78O_n-AfNr3lSbp_HDKjibzEd1sBE



### Mise à jour d'un utlisateur
PATCH http://localhost:4000/api/users/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI4LCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNzA3ODc2NjA2fQ.pWXKMEoWgeIsAr78O_n-AfNr3lSbp_HDKjibzEd1sBE
Content-Type: application/json

{
    "enterprise": "DOD",
    "email": "Pépé.bon@dod.com",
    "firstname": "Mémé",
    "lastname": "Bon",
    "password": "Jeanbon0",
    "position": "Chef d'atelier",
    "process": "Production",
    "roleId": 1
}


### Suppression d'un Utilisateur
DELETE http://localhost:4000/api/users/41
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI4LCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNzA3ODc2NjA2fQ.pWXKMEoWgeIsAr78O_n-AfNr3lSbp_HDKjibzEd1sBE



### Récupération de tous les événements
GET http://localhost:4000/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI4LCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNzA3ODc2NjA2fQ.pWXKMEoWgeIsAr78O_n-AfNr3lSbp_HDKjibzEd1sBE

### Récupération de tous les événements
GET http://localhost:4000/api/eventorigin/titles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI4LCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNzA3ODc2NjA2fQ.pWXKMEoWgeIsAr78O_n-AfNr3lSbp_HDKjibzEd1sBE









### Récupération d'un seul évènement
GET http://localhost:4000/api/events/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI4LCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNzA3ODc2NjA2fQ.pWXKMEoWgeIsAr78O_n-AfNr3lSbp_HDKjibzEd1sBE


### Création d'un évènement
POST http://localhost:4000/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI4LCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNzA3ODc2NjA2fQ.pWXKMEoWgeIsAr78O_n-AfNr3lSbp_HDKjibzEd1sBE
Content-Type: application/json

{
    "site_name" :"Tour Karras",
    "site_number": "56897",
    "site_town": "Rouen",
    "witness" : "Célèste ",
    "event_description" : "Paul ne porte pas son harnais alors qu'il se trouve sur une nacelle",
    "info_sse_description" : "Rappel fait",
    "status_event" : true,
    "corrective_action" : "Une nouvelle formation sera nécessaire",
    "deadline_action": "2024-02-14T23:00:00.000Z",
    "action_pilot" : "Babar",
    "action_status": false,
    "user_id": 38,
    "event_nature_id": 1,
    "risk_level_1_id": 1,
    "risk_level_2_id": 1,
    "risk_level_3_id": 1,
    "event_type_id": 1,
    "detection_context_id": 1,
    "event_origin_id": 1,
    "work_phase_id": 1

}

### Modification événement

PATCH  http://localhost:4000/api/events/135
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ3LCJ1c2VyUm9sZSI6InVzZXIiLCJpYXQiOjE3MDgyMDA1Mjd9.0yB9y6ZG-h_Po8HtYDJDunk_LqskBXvai6i7yjCsJN0
Content-Type: application/json

{
    "site_name" :"Monparnasse",
    "site_number": "80000",
    "site_town": "Paris",
    "witness" : null,
    "event_description" : "Le filet anti-chute s'est envolé dans la nuit",
    "info_sse_description" : "SSE informé immédiatement",
    "status_event" : true,
    "corrective_action" : "Le filet doit être décroché et remis en place",
    "deadline_action": "2024-02-14T23:00:00.000Z",
    "action_pilot" : "Astride",
    "action_status": false,
    "criticality" : null,
    "user_id": 39,
    "event_nature_id": 1,
    "risk_level_1_id": 16,
    "risk_level_2_id": null,
    "risk_level_3_id": null,
    "event_type_id": 1,
    "detection_context_id": 1,
    "event_origin_id": 1,
    "work_phase_id": 1

}

###

### Suppression d'un événement
DELETE http://localhost:4000/api/events/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ3LCJ1c2VyUm9sZSI6InVzZXIiLCJpYXQiOjE3MDgyMDA1Mjd9.0yB9y6ZG-h_Po8HtYDJDunk_LqskBXvai6i7yjCsJN0


### récupération d'évènements en fonction de l'entreprise dans un lintervalle de temps donné
POST http://localhost:4000/api/stats/eventsdates
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI4LCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNzA3ODc2NjA2fQ.pWXKMEoWgeIsAr78O_n-AfNr3lSbp_HDKjibzEd1sBE
Content-Type: application/json

{
"endDate": "2024-02-10",
"startDate" : "2024-02-26",
"enterpriseName" : "DOD"

}


### récupération d'évènements en fonction de l'entreprise dans un lintervalle de temps donné
POST http://localhost:4000/api/stats/numberevents
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI4LCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNzA3ODc2NjA2fQ.pWXKMEoWgeIsAr78O_n-AfNr3lSbp_HDKjibzEd1sBE
Content-Type: application/json

{
"endDate": "2024-02-10",
"startDate" : "2024-02-26",
"enterpriseName" : "DOD"

}

### récupération d'événements en fonction de l'utilisateur qui les a déclarés

GET http://localhost:4000/api/user-events/39
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM5LCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNzA5Mzk5Njk4fQ.uM3oecVPgTPXRB7j80riVo9NdwIDw1be907KuMvXb5E